# Generated by Django 6.1.1 on 2026-09-11 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0002_student_user_teacher_user_achievement_assignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=12),
        ),
        migrations.AddField(
            model_name='teacher',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=12),
        ),
        migrations.AddField(
            model_name='teacher',
            name='assigned_classes',
            field=models.ManyToManyField(blank=True, related_name='subject_teachers', to='marks.class'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='duties',
            field=models.CharField(blank=True, help_text='Additional duties, such as house or club responsibility', max_length=255),
        ),
        migrations.AddField(
            model_name='teacher',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('ahm', 'Assistant House Master/Matron'), ('hm', 'House Master/Matron'), ('other', 'Other duty')], default='teacher', max_length=20),
        ),
        migrations.CreateModel(
            name='StudentClassChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_change_requests', to='marks.class')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_class_change_requests', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_change_requests', to='marks.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='requested', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_student_leaves', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='marks.student')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('captain', 'Captain'), ('vice_captain', 'Vice Captain'), ('prefect', 'Prefect'), ('other', 'Other role')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='marks.student')),
            ],
            options={
                'ordering': ['-is_active', '-start_date'],
            },
        ),
    ]
